---
title: "Transcriptomics Project Proposal"
subtitle: ""
author: "Roa Hanoun & Jero Eyras"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    toc_float: false
    number_sections: false
    theme: cosmo
    highlight: tango
fontsize: 12pt
geometry: margin=1in
---

## Chosen Project

```{=html}
<pre>
<b>Environmental fluoxetine promotes skin cell proliferation and wound healing</b>
<a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE268987">GEO Page</a>
</pre>
```

### Description

This study explores how **environment pharmaceutics** like fluoxetine, also known as Prozac, affect **wound healing**. In this case, they describe environment pharmaceutics as the concerning pollution of water systems with pharmaceutical and care products. They talk about fluoxetine as an example of a **selective serotonin reuptake inhibitor**, and claim enhanced wound healing is the effect of **cell proliferation** and **serotonin signaling**.

*"Transcriptomic analysis revealed 350 differentially expressed genes after exposure"*<br> - **Downregulated genes**, related to mitochondrial function and metabolism.<br> - **Upregulated genes**, associated with cell proliferation and tissue morphogenesis.

The underlying motivation for this study is the well known effects of pharmaceutical water pollution on aquatic animals, and the unkown effects on humans. They conclude that there is enough evidence to justify further studies, for instance potential health risks or benefits on humans and even clinical applications of fluoxetine for wound healing.

### Data Sets

|           Sample Group           | Time Since Exposure | Replicate Amount |
|:--------------------------------:|:-------------------:|:----------------:|
|          Control Group           |       6 hours       |        4         |
|          Control Group           |      36 hours       |        4         |
| Exposed to 0.5µg/L of Fluoxetine |       6 hours       |        4         |
| Exposed to 0.5µg/L of Fluoxetine |      36 hours       |        4         |

### Tools

RNA Sequencing:<br>
- **DESeq2** R package, "gene expression was log2 transformed, and the calculated p-values were adjusted using the Benjamini–Hochberg correction for false discovery rate (padj). Genes significantly (padj ≤0.05) up- or down-regulated with a gene symbol/ID annotation were used in subsequent analysis"

### Statistical Analyses

Parametric data:<br>
- **T-test**, for binay comparisons.<br>
- **ANOVA** followed by **Tukey post-hoc tests**, for multiple comparisons.

Non-parametric data (protein microarrays):<br>
- **PERMANOVA**, using Adonis function from [vegan R package](https://cran.r-project.org/web/packages/vegan/index.html) in R Studio (R 4.1.2).

Phosphoproteomics:<br>
- **FragPipe-Analyst** R package, "statistical comparison of relative phosphopeptide abundance between groups", "differences in phosphorylation levels cut at padj <0.00001 and log2 fold >5".

## Action Plan

We will attempt to follow the procedures taken in this study. For this we can look at the results section in the scientific article, and follow the sections relevant to transcriptomics analysis.

### Transcriptomics Analysis

Section 3.2 in the scientific article. In this section they classify and plot the differentially expressed genes with a heatmap chart and the up and downregulated genes using a volcano plot. The previously mentioned tool DESeq2 is used here.

### Enrichment Analysis

By pointing out what genes are up and downregulated we can attribute certain genes to this enhanced wound healing or even find possible risks and side effects. Since 350 genes are differentially expressed, some sort of software is used for this task.

### Additional Questions

Given the conclusions arrived to in the article, we can formulate some followup questions:<br>
- Are there more gene functions up or downregulated than the ones stated in the article? This could be visible right after enrichment analysis or through additional data analysis steps.<br>
- Has the same conclusion been reached to before? Or is there some conflicting research out there? There's possibly other scientific articles out there that could provide a new perspective on the matter.
